export const settings_input_field_style = {
  borderRadius: `24px`,
  height: `60px`,
  border: `1px solid`,
  borderColor: `matador_border_color.100`,
  boxShadow: ` 0px 1.333px 2.667px 0px rgba(16, 24, 40, 0.05)`,
  padding: `19px`,
  color: `matador_text.300`,
  fontSize: `16px`,
  fontWeight: `400`,
  lineHeight: `150%`,
  letterSpacing: `0.16px`,
  _placeholder: {
    color: `matador_text.300`,
    opacity: `1`,
    fontSize: `16px`,
    fontWeight: `400`,
    lineHeight: `150%`,
    letterSpacing: `0.16px`,
  },
  labelStyles: {
    fontSize: `16px`,
    color: `matador_form.label`,
    fontWeight: `400`,
    lineHeight: `140%`,
  },
};

export const settings_select_field_style = {
  borderRadius: `24px`,
  h: `60px`,
  border: `1px solid`,
  borderColor: `matador_border_color.100 !important`,
  boxShadow: `0px 1px 2px 0px rgba(16, 24, 40, 0.05)`,
  color: `matador_text.300`,
  fontSize: `16px`,
  fontWeight: `400`,
  lineHeight: `150%`,
  letterSpacing: `0.16px`,
  _placeholder: {
    color: `matador_text.300`,
    fontSize: `16px`,
    fontWeight: `400`,
    lineHeight: `150%`,
    letterSpacing: `0.16px`,
  },
  labelStyles: {
    fontSize: `16px`,
    color: `matador_form.label`,
    fontWeight: `400`,
    lineHeight: `140%`,
  },
  // padding: `10px 14px`,
};
